name: dotnet7-xunit-nuget

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Exibir instalações do .NET pré-existentes
      run: |
        dotnet --list-sdks
        echo '**** Versão default assumida para o .NET ****'
        dotnet --version
    - name: Setup .NET 7 Preview 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.100-preview.7.22377.5
